[workspace]
resolver = "2"
members = [
    "crates/sonic-ux-core",
    "crates/sonic-ux-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Sepzie/SonicUX"

[profile.release]
opt-level = "s"
lto = true
